apiVersion: v1
kind: Namespace
metadata:
  name: openldap
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: openldap-selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openldap
spec:
  dnsNames:
    - ldap.openldap.svc
    - ldap.openldap.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: openldap-selfsigned-issuer
  secretName: openldap-server-cert
---
apiVersion: v1
kind: Service
metadata:
  name: ldap
spec:
  ports:
    - name: ldap
      port: 389
      protocol: TCP
      targetPort: ldap
    - name: ldaps
      port: 636
      protocol: TCP
      targetPort: ldaps
  selector:
    app: openldap
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openldap
spec:
  selector:
    matchLabels:
      app: openldap
  serviceName: openldap
  replicas: 1
  template:
    metadata:
      labels:
        app: openldap
    spec:
      containers:
        - name: openldap
          image: bitnamilegacy/openldap:2.6.10-debian-12-r4
          env:
            - name: BITNAMI_DEBUG
              value: "yes"
            - name: LDAP_CONFIG_ADMIN_ENABLED
              value: "yes"
            - name: LDAP_ENABLE_TLS
              value: "yes"
            - name: LDAP_TLS_CERT_FILE
              value: /var/run/tls/tls.crt
            - name: LDAP_TLS_KEY_FILE
              value: /var/run/tls/tls.key
            - name: LDAP_TLS_CA_FILE
              value: /var/run/tls/ca.crt
          ports:
            - containerPort: 1389
              name: ldap
            - containerPort: 1636
              name: ldaps
          volumeMounts:
            - name: data
              mountPath: /bitnami/openldap
            - name: server-cert
              mountPath: /var/run/tls
              readOnly: true
            - name: customize
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: server-cert
          secret:
            secretName: openldap-server-cert
        - name: customize
          configMap:
            name: openldap-customize
            defaultMode: 0555
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
