apiVersion: klap.ripolin.github.com/v1alpha1
kind: Entry
metadata:
  labels:
    app.kubernetes.io/name: klap
    app.kubernetes.io/managed-by: kustomize
  name: entry-sample
spec:
  # TODO(user): Add fields here
