apiVersion: v1
kind: Secret
metadata:
  name: ldap-server
  namespace: default
type: Opaque
stringData:
  url: ldap://ldap.openldap.svc:389
  bind_dn: cn=admin,dc=example,dc=org
  password: changeme
  base_dn: dc=example,dc=org
  start_tls: "false"
