apiVersion: v1
kind: Secret
metadata:
  name: ldap-tls
  namespace: default
type: Opaque
stringData:
  ca.crt: |-
    -----BEGIN CERTIFICATE-----
    MIID...REPLACE-WITH-REAL-CA...
    -----END CERTIFICATE-----
